// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTi-EFZQyJOnRVqJio-fgKXadSvjPCpeI',
    appId: '1:905655582501:web:70b4af6f6185281f6ae4cc',
    messagingSenderId: '905655582501',
    projectId: 'demoleng-a6300',
    authDomain: 'demoleng-a6300.firebaseapp.com',
    storageBucket: 'demoleng-a6300.appspot.com',
    measurementId: 'G-J5B69VN4NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn0daOPDn3sBHfLJOS6sel01o8lS8WBlc',
    appId: '1:905655582501:android:2f4f4799613180c26ae4cc',
    messagingSenderId: '905655582501',
    projectId: 'demoleng-a6300',
    storageBucket: 'demoleng-a6300.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7-fIC4sWX0bYu_fsvwA1X3Gr4EuITxRs',
    appId: '1:905655582501:ios:585069f834ca51166ae4cc',
    messagingSenderId: '905655582501',
    projectId: 'demoleng-a6300',
    storageBucket: 'demoleng-a6300.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7-fIC4sWX0bYu_fsvwA1X3Gr4EuITxRs',
    appId: '1:905655582501:ios:585069f834ca51166ae4cc',
    messagingSenderId: '905655582501',
    projectId: 'demoleng-a6300',
    storageBucket: 'demoleng-a6300.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTi-EFZQyJOnRVqJio-fgKXadSvjPCpeI',
    appId: '1:905655582501:web:0096740f53383f696ae4cc',
    messagingSenderId: '905655582501',
    projectId: 'demoleng-a6300',
    authDomain: 'demoleng-a6300.firebaseapp.com',
    storageBucket: 'demoleng-a6300.appspot.com',
    measurementId: 'G-SNZBRC5P4B',
  );
}
